### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bharathraj123456** [pablolluchr/emotion-detection-app#1]
Traceback (most recent call last):
  File "C:\Users\emotion-detection-app-master\live_convolutions.py", line 27, in <module>
    model = load_model("action_unit_cnn.hdf5", custom_objects=dependencies)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at action_unit_cnn.hdf5

**Comment by bharathraj123456** [comment]
sir can help me to d bug the above error
